### ISSUE TITLE
load countries by default [p3]

### ISSUE THREAD

**Issue by nicolasaltori** [echerost/GranitoSoftware#2]
sarebbe comodo che già al primo accesso sul programma tutti i dati inseriti venissero mostrati di default in anteprima, senza dover cliccare sul tasto "load" per poter visionare i dati già inseriti

grazie

**Comment by echerost** [comment]
intendi tutti i dati, ad esempio anche gli impiegati, i tipi di impiegati, ecc, oppure solo quelli relativi a countries?
