### ISSUE TITLE
Add Employee - Crash [p9999]

### ISSUE THREAD

**Issue by meng86** [echerost/GranitoSoftware#3]
![immagine](https://user-images.githubusercontent.com/37342930/37354480-0d9e2b40-26e2-11e8-978b-3b37d51f0038.png)

Inserendo un nuovo "impiegato", che non ha la partita IVA, il software prima restituisce un errore "Dati non validi" e subito dopo va totalmente in crash.

**Comment by echerost** [comment]
L'errore è dovuto al fatto che il DB richeide obbligatoriamente una partita IVA. Prova ad inserire il codice fiscale sia nel giusto spazio che nel campo della partita iva
