### ISSUE TITLE
Wallpaper modification [p100]

### ISSUE THREAD

**Issue by meng86** [echerost/GranitoSoftware#5]
Se possibile, suggerisco di modificare lo sfondo (wallpaper) della schermata di entrata nel software, dove adesso c'è un sasso in granito. Allego due immagini tra cui scegliere. Lascio la scelta finale a Daniele, in base al risultato estetico.

![immagine1](https://user-images.githubusercontent.com/37342930/37641692-05b95fce-2c1b-11e8-9e54-bc201a357a81.jpg)
![immagine2](https://user-images.githubusercontent.com/37342930/37641693-05d5d6ae-2c1b-11e8-977f-6bf19a271c49.jpg)

**Comment by echerost** [comment]
Fatto :)  1.0.1.5
